#!/usr/bin/env node
/*jslint sloppy: true */
/*global require: false, console: false, node: false, process: false */

var coffee = require('coffee-script'),
    fs = require('fs');

try {
    coffee.compile(fs.readFileSync('/dev/stdin').toString());
} catch (e) {
    var str = e.toString(),
        match = str.match(/on line (\d+)/i),
        line = match ? match[1] : 1;

    console.log(line + ':' + str);
}

/* vim: set ft=javascript : */
