#!/usr/bin/env node
/*jslint sloppy: true */
/*global require: false, console: false, node: false, process: false */

var coffee = require('coffee-script'),
    fs = require('fs');

try {
    coffee.compile(fs.readFileSync('/dev/stdin').toString());
} catch (e) {
    var str = e.toString();
    if (/^Error/.test(str)) {
        console.log(str.replace(/Error: Parse error on line (\d+): /, '$1:'));
    } else if (/^SyntaxError/.test(str)) {
        // var line = str.replace(/.+on line (\d+).+/, '$1');
        str = str.replace(/SyntaxError: /, '');
        
        console.log(str.replace(/()(\d+): /, '$1:'));
    }
}

/* vim: set ft=javascript : */
